# Generated by Django 5.2.11 on 2026-03-09 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_academicclass_arm_name_academicclass_base_class'),
        ('dashboard', '0003_schoolprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='assignment_label',
            field=models.CharField(default='Project/Assignment', max_length=40),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='auto_comment_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='ca1_label',
            field=models.CharField(default='1st CA', max_length=40),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='ca2_label',
            field=models.CharField(default='2nd CA', max_length=40),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='ca3_label',
            field=models.CharField(default='3rd CA', max_length=40),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='promotion_attendance_threshold',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=5),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='promotion_average_threshold',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='report_footer',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='require_result_access_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='branding/stamp/'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patroned_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StudentClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_held', models.CharField(blank=True, max_length=120)),
                ('significant_contribution', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_club_memberships', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dashboard.club')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('club__name', 'student__username'),
                'constraints': [models.UniqueConstraint(fields=('student', 'club', 'session'), name='unique_student_club_membership_per_session')],
            },
        ),
    ]
