# Generated by Django 5.2.11 on 2026-03-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_weeklychallenge_and_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='dean_comment_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='doctor_remark_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_comment_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='promotion_policy_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='teacher_comment_guidance',
            field=models.TextField(blank=True),
        ),
    ]
