# Generated by Django 5.2.11 on 2026-04-07 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_academicclass_arm_name_academicclass_base_class'),
        ('dashboard', '0007_publicsitesubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('instructions', models.TextField()),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='learning/lms_assignments/')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('allow_late_submissions', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('due_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LMSAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_text', models.TextField(blank=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='learning/lms_submissions/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('REVISION_REQUIRED', 'Revision Required')], default='DRAFT', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='LMSClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('overview', models.TextField(blank=True)),
                ('welcome_note', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('teacher_assignment__academic_class__code', 'teacher_assignment__subject__name'),
            },
        ),
        migrations.CreateModel(
            name='LMSDiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_staff_note', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LMSLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='learning/lms_lessons/')),
                ('external_url', models.URLField(blank=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=20)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='LMSLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='LMSModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.RenameIndex(
            model_name='publicsitesubmission',
            new_name='dashboard_p_submiss_57efe3_idx',
            old_name='dashboard_p_submis_7a8e95_idx',
        ),
        migrations.RenameIndex(
            model_name='publicsitesubmission',
            new_name='dashboard_p_contact_89a78b_idx',
            old_name='dashboard_p_contact_a36db8_idx',
        ),
        migrations.RenameIndex(
            model_name='publicsitesubmission',
            new_name='dashboard_p_intende_36c39d_idx',
            old_name='dashboard_p_intende_915938_idx',
        ),
        migrations.AddField(
            model_name='lmsassignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dashboard.lmsassignment'),
        ),
        migrations.AddField(
            model_name='lmsassignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_lms_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lmsassignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lmsclassroom',
            name='teacher_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lms_classroom', to='academics.teachersubjectassignment'),
        ),
        migrations.AddField(
            model_name='lmsassignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.lmsclassroom'),
        ),
        migrations.AddField(
            model_name='lmsdiscussioncomment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_comments', to='dashboard.lmsassignment'),
        ),
        migrations.AddField(
            model_name='lmsdiscussioncomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_discussion_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lmsdiscussioncomment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='dashboard.lmsclassroom'),
        ),
        migrations.AddField(
            model_name='lmslessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='dashboard.lmslesson'),
        ),
        migrations.AddField(
            model_name='lmslessonprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lmsmodule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='dashboard.lmsclassroom'),
        ),
        migrations.AddField(
            model_name='lmslesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='dashboard.lmsmodule'),
        ),
        migrations.AddField(
            model_name='lmsdiscussioncomment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_comments', to='dashboard.lmsmodule'),
        ),
        migrations.AddField(
            model_name='lmsassignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='dashboard.lmsmodule'),
        ),
        migrations.AddConstraint(
            model_name='lmsassignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_lms_submission_per_assignment_student'),
        ),
        migrations.AddConstraint(
            model_name='lmslessonprogress',
            constraint=models.UniqueConstraint(fields=('lesson', 'student'), name='unique_lms_lesson_progress_per_student'),
        ),
    ]
