# Generated by Django 5.2.11 on 2026-04-08 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_lmsassignment_lmsassignmentsubmission_lmsclassroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicsitesubmission',
            name='admissions_status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='NEW', max_length=16),
        ),
        migrations.AddField(
            model_name='publicsitesubmission',
            name='application_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='publicsitesubmission',
            name='application_fee_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicsitesubmission',
            name='application_fee_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='publicsitesubmission',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicsitesubmission',
            name='generated_admission_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='publicsitesubmission',
            name='linked_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_admission_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicsitesubmission',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='UNPAID', max_length=16),
        ),
        migrations.AddField(
            model_name='publicsitesubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicsitesubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_public_site_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='publicsitesubmission',
            index=models.Index(fields=['submission_type', 'admissions_status', 'payment_status'], name='dashboard_p_submiss_d8d4d3_idx'),
        ),
    ]
