# Generated by Django 5.2.11 on 2026-04-08 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_publicsitesubmission_admissions_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('meta', models.CharField(default='School Event', max_length=120)),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('summary', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public_site/events/')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_public_event_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'event_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PublicGalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='public_site/gallery/categories/')),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_public_gallery_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PublicGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('image', models.ImageField(upload_to='public_site/gallery/images/')),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.publicgallerycategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_public_gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PublicNewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(default='School News', max_length=120)),
                ('published_on', models.DateField(default=django.utils.timezone.localdate)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='public_site/news/')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_public_news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', '-published_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PublicWebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='PRIMARY', editable=False, max_length=16, unique=True)),
                ('hero_eyebrow', models.CharField(default="Welcome to Notre Dame Girls' Academy", max_length=160)),
                ('hero_title', models.CharField(default='Educating Girls for Life', max_length=220)),
                ('hero_subtitle', models.TextField(default="Notre Dame Girls' Academy, Kuje-Abuja forms confident, competent, and compassionate young women through purposeful learning, Catholic formation, full boarding, and disciplined care.")),
                ('principal_welcome_title', models.CharField(default='A welcome from the Principal', max_length=180)),
                ('principal_welcome_message', models.TextField(default="Welcome to Notre Dame Girls' Academy, a Catholic secondary school dedicated to forming confident, competent, and compassionate young women.")),
                ('principal_welcome_support', models.TextField(default='We partner with parents to nurture Gospel values, disciplined study habits, strong character, and the full potential of every girl entrusted to our care.')),
                ('footer_statement', models.TextField(default='Educating girls for life through strong academics, boarding structure, faith formation, and disciplined student growth.')),
                ('chat_welcome_text', models.TextField(default='Hello. I am Julie. I can guide you on admissions, fees, boarding, subjects, screening, and school life.')),
                ('chat_management_wait_text', models.TextField(default='Connecting you to management. Please wait...')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_public_website_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Website Settings',
                'verbose_name_plural': 'Public Website Settings',
            },
        ),
    ]
