# Generated by Django 5.2.11 on 2026-04-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_publiceventpost_publicgallerycategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicAdmissionPaymentTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=80, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("PAYSTACK", "Paystack"), ("FLUTTERWAVE", "Flutterwave")],
                        default="PAYSTACK",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("INITIALIZED", "Initialized"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("callback_url", models.CharField(blank=True, max_length=320)),
                ("authorization_url", models.CharField(blank=True, max_length=500)),
                ("gateway_reference", models.CharField(blank=True, max_length=180)),
                ("initialized_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="dashboard.publicsitesubmission",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="publicadmissionpaymenttransaction",
            index=models.Index(fields=["reference"], name="dashboard_p_referen_fcd76f_idx"),
        ),
        migrations.AddIndex(
            model_name="publicadmissionpaymenttransaction",
            index=models.Index(fields=["submission", "status", "created_at"], name="dashboard_p_submiss_ae2d3a_idx"),
        ),
        migrations.AddIndex(
            model_name="publicadmissionpaymenttransaction",
            index=models.Index(fields=["provider", "status"], name="dashboard_p_provide_4f6bd2_idx"),
        ),
    ]
