# Generated by Django 5.2.11 on 2026-04-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_publicadmissionpaymenttransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publicadmissionpaymenttransaction',
            new_name='dashboard_p_referen_8f3f82_idx',
            old_name='dashboard_p_referen_fcd76f_idx',
        ),
        migrations.RenameIndex(
            model_name='publicadmissionpaymenttransaction',
            new_name='dashboard_p_submiss_c76881_idx',
            old_name='dashboard_p_submiss_ae2d3a_idx',
        ),
        migrations.RenameIndex(
            model_name='publicadmissionpaymenttransaction',
            new_name='dashboard_p_provide_180569_idx',
            old_name='dashboard_p_provide_4f6bd2_idx',
        ),
    ]
