# Generated by Django 5.2.11 on 2026-04-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_rename_dashboard_p_referen_fcd76f_idx_dashboard_p_referen_8f3f82_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicwebsitesettings",
            name="chat_welcome_text",
            field=models.TextField(
                default="Hello. I am Smart NDGA. I can guide you on admissions, boarding, subjects, screening, school life, and contact details."
            ),
        ),
        migrations.AlterField(
            model_name="publicwebsitesettings",
            name="hero_eyebrow",
            field=models.CharField(
                default="Welcome to Notre Dame Girls' Academy, Kuje Abuja",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="publicwebsitesettings",
            name="hero_subtitle",
            field=models.TextField(
                default="Academic excellence, disciplined boarding, and strong Catholic character formation for girls in a safe learning community."
            ),
        ),
        migrations.AlterField(
            model_name="publicwebsitesettings",
            name="hero_title",
            field=models.CharField(
                default="A Leading Catholic Girls' Boarding School in Abuja Focused on Academic Excellence and Character Formation",
                max_length=220,
            ),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="school_name",
            field=models.CharField(default="Notre Dame Girls' Academy", max_length=180),
        ),
    ]
