# Generated by Django 5.2.11 on 2026-03-03 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_academicsession_closed_at_academicsession_closed_by_and_more'),
        ('accounts', '0003_staffprofile_profile_photo_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='graduated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduated_student_profiles', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
