# Generated by Django 5.2.11 on 2026-03-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated'), ('TRANSFERRED', 'Transferred'), ('EXITED', 'Exited')], default='ACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='lifecycle_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='disciplinary_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lifecycle_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lifecycle_state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
    ]
