# Generated by Django 5.2.11 on 2026-03-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffprofile_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
