# Generated by Django 5.2.11 on 2026-03-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_permission_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
