# Generated by Django 5.2.11 on 2026-03-02 19:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_subject_category_studentsubjectenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS'), ('GATEWAY', 'Gateway'), ('OTHER', 'Other')], default='CASH', max_length=16)),
                ('gateway_reference', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_void', models.BooleanField(default=False)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_finance_payments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_payments', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_payments', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payments', to='academics.term')),
            ],
            options={
                'ordering': ('-payment_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=40, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_finance_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.payment')),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='Use first day of the salary month.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('HOLD', 'On Hold')], default='PENDING', max_length=12)),
                ('payment_reference', models.CharField(blank=True, max_length=140)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_finance_salaries', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_salary_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-month', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='StudentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('target_type', models.CharField(choices=[('STUDENT', 'Student'), ('CLASS', 'Class')], default='STUDENT', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_charges', to='academics.academicclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_charges', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_student_charges', to='academics.academicsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_charges', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_student_charges', to='academics.term')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('UTILITIES', 'Utilities'), ('FACILITIES', 'Facilities'), ('OPERATIONS', 'Operations'), ('ACADEMICS', 'Academics'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], default='OPERATIONS', max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField(blank=True)),
                ('receipt_attachment', models.FileField(blank=True, null=True, upload_to='finance/expenses/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-expense_date', '-created_at'),
                'indexes': [models.Index(fields=['expense_date', 'category'], name='finance_exp_expense_be3fd2_idx'), models.Index(fields=['is_active', 'expense_date'], name='finance_exp_is_acti_203469_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'session', 'payment_date'], name='finance_pay_student_4398e0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_void', 'payment_date'], name='finance_pay_is_void_8b1b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='finance_rec_receipt_e3529a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payload_hash'], name='finance_rec_payload_7416d2_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['month', 'status'], name='finance_sal_month_19232e_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['is_active', 'month'], name='finance_sal_is_acti_a9f3d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='salaryrecord',
            constraint=models.UniqueConstraint(fields=('staff', 'month'), name='unique_staff_salary_month'),
        ),
        migrations.AddConstraint(
            model_name='salaryrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='salary_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='studentcharge',
            index=models.Index(fields=['session', 'target_type', 'is_active'], name='finance_stu_session_d537ee_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcharge',
            index=models.Index(fields=['student', 'is_active'], name='finance_stu_student_7c4f42_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcharge',
            index=models.Index(fields=['academic_class', 'is_active'], name='finance_stu_academi_ab4a25_idx'),
        ),
    ]
