# Generated by Django 5.2.11 on 2026-03-05 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_academicsession_closed_at_academicsession_closed_by_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('ICT', 'ICT'), ('LAB', 'Lab'), ('FURNITURE', 'Furniture'), ('SPORTS', 'Sports'), ('TRANSPORT', 'Transport'), ('FACILITY', 'Facility'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('quantity_total', models.PositiveIntegerField(default=1)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('acquisition_reference', models.CharField(blank=True, max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('asset_code',),
            },
        ),
        migrations.CreateModel(
            name='InventoryAssetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('ISSUE_OUT', 'Issue Out'), ('RETURN_IN', 'Return In'), ('WRITE_OFF', 'Write Off')], max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=140)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='finance.inventoryasset')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack')], default='PAYSTACK', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIALIZED', 'Initialized'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('callback_url', models.CharField(blank=True, max_length=320)),
                ('authorization_url', models.CharField(blank=True, max_length=500)),
                ('gateway_reference', models.CharField(blank=True, max_length=180)),
                ('initialized_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_gateway_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_transaction', to='finance.payment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_gateway_transactions', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_gateway_transactions', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_gateway_transactions', to='academics.term')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FinanceReminderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reminder_type', models.CharField(choices=[('UPCOMING', 'Upcoming Due'), ('OVERDUE', 'Overdue')], max_length=16)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='SENT', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('charge_ids', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reminders_sent', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_reminder_dispatches', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_reminder_dispatches', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reminder_dispatches', to='academics.term')),
            ],
            options={
                'ordering': ('-reminder_date', '-created_at'),
                'indexes': [models.Index(fields=['reminder_date', 'reminder_type', 'status'], name='finance_fin_reminde_ce8764_idx'), models.Index(fields=['student', 'session', 'reminder_date'], name='finance_fin_student_d5c9e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'session', 'term', 'reminder_date', 'reminder_type'), name='unique_finance_reminder_per_student_day')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryasset',
            index=models.Index(fields=['category', 'status', 'is_active'], name='finance_inv_categor_aeb18b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryasset',
            index=models.Index(fields=['asset_code'], name='finance_inv_asset_c_4ba46b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryassetmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='finance_inv_movemen_b4b811_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryassetmovement',
            index=models.Index(fields=['asset', 'created_at'], name='finance_inv_asset_i_6ec535_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewaytransaction',
            index=models.Index(fields=['status', 'created_at'], name='finance_pay_status_306411_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewaytransaction',
            index=models.Index(fields=['student', 'session', 'status'], name='finance_pay_student_0466b5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewaytransaction',
            index=models.Index(fields=['provider', 'reference'], name='finance_pay_provide_b4e338_idx'),
        ),
    ]
