# Generated by Django 5.2.11 on 2026-03-06 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_inventoryasset_inventoryassetmovement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='PRIMARY', editable=False, max_length=16, unique=True)),
                ('school_bank_name', models.CharField(blank=True, max_length=140)),
                ('school_account_name', models.CharField(blank=True, max_length=160)),
                ('school_account_number', models.CharField(blank=True, max_length=64)),
                ('include_bank_details_in_messages', models.BooleanField(default=False)),
                ('show_on_receipt_pdf', models.BooleanField(default=False)),
                ('show_on_result_pdf', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_finance_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance Institution Profile',
                'verbose_name_plural': 'Finance Institution Profile',
            },
        ),
    ]
