# Generated by Django 5.2.11 on 2026-04-07 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_academicclass_arm_name_academicclass_base_class'),
        ('finance', '0005_alter_paymentgatewaytransaction_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDeltaSyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cursor_name', models.CharField(max_length=40, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_reference', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('cursor_name',),
            },
        ),
        migrations.CreateModel(
            name='FinanceReconciliationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(default='CLOUD_TO_LAN', max_length=24)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported'), ('DUPLICATE', 'Duplicate'), ('CONFLICT', 'Conflict'), ('SKIPPED', 'Skipped')], default='IMPORTED', max_length=16)),
                ('reference', models.CharField(max_length=120)),
                ('gateway_reference', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='source_authority',
            field=models.CharField(choices=[('LAN', 'LAN'), ('CLOUD', 'Cloud')], default='LAN', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewaytransaction',
            name='source_authority',
            field=models.CharField(choices=[('LAN', 'LAN'), ('CLOUD', 'Cloud')], default='LAN', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentgatewaytransaction',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['source_authority', 'source_updated_at'], name='finance_pay_source__a11694_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewaytransaction',
            index=models.Index(fields=['source_authority', 'source_updated_at'], name='finance_pay_source__ad5f5a_idx'),
        ),
        migrations.AddField(
            model_name='financereconciliationevent',
            name='gateway_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_events', to='finance.paymentgatewaytransaction'),
        ),
        migrations.AddField(
            model_name='financereconciliationevent',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_events', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='financereconciliationevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_finance_reconciliation_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financereconciliationevent',
            index=models.Index(fields=['status', 'created_at'], name='finance_fin_status_35dba1_idx'),
        ),
        migrations.AddIndex(
            model_name='financereconciliationevent',
            index=models.Index(fields=['reference'], name='finance_fin_referen_d2f5e3_idx'),
        ),
    ]
