# Generated by Django 5.2.11 on 2026-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_financedeltasynccursor_financereconciliationevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinstitutionprofile',
            name='application_form_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financeinstitutionprofile',
            name='application_form_fee_note',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
