# Generated by Django 5.2.11 on 2026-03-01 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classsubject_formteacherassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.academicclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('academic_class__code', 'student__username'),
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_class', 'session'), name='unique_student_class_session_enrollment'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'session'), name='unique_active_student_enrollment_per_session')],
            },
        ),
    ]
