# Generated by Django 5.2.11 on 2026-03-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentclassenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SCIENCE', 'Science'), ('ARTS', 'Arts'), ('COMMERCIAL', 'Commercial'), ('VOCATIONAL', 'Vocational')], default='GENERAL', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_enrollments', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.subject')),
            ],
            options={
                'ordering': ('student__username', 'subject__name'),
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'session'), name='unique_student_subject_per_session')],
            },
        ),
    ]
