# Generated by Django 5.2.11 on 2026-03-03 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subject_category_studentsubjectenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_academic_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SessionPromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('PROMOTED', 'Promoted'), ('RETAINED', 'Retained'), ('GRADUATED', 'Graduated')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('from_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_from_records', to='academics.academicclass')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_session_promotion_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_promotion_records', to=settings.AUTH_USER_MODEL)),
                ('to_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_to_records', to='academics.academicclass')),
            ],
            options={
                'ordering': ('student__username',),
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='unique_promotion_record_per_student_session')],
            },
        ),
    ]
