# Generated by Django 5.2.11 on 2026-03-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_campus_academicclass_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='arm_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='base_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arm_classes', to='academics.academicclass'),
        ),
    ]
