# Generated by Django 5.2.11 on 2026-06-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_academicclass_arm_name_academicclass_base_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionpromotionrecord',
            options={'ordering': ('student__last_name', 'student__first_name', 'student__student_profile__middle_name', 'student__student_profile__student_number', 'student__username')},
        ),
        migrations.AlterModelOptions(
            name='studentclassenrollment',
            options={'ordering': ('academic_class__code', 'student__last_name', 'student__first_name', 'student__student_profile__middle_name', 'student__student_profile__student_number', 'student__username')},
        ),
        migrations.AlterModelOptions(
            name='studentsubjectenrollment',
            options={'ordering': ('student__last_name', 'student__first_name', 'student__student_profile__middle_name', 'student__student_profile__student_number', 'student__username', 'subject__name')},
        ),
    ]
