# Generated by Django 5.2.11 on 2026-03-02 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examblueprint',
            name='allow_retake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examblueprint',
            name='auto_show_result_on_submit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examblueprint',
            name='finalize_on_logout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examblueprint',
            name='objective_writeback_target',
            field=models.CharField(choices=[('NONE', 'No Writeback'), ('CA1', 'CA1'), ('CA2', 'CA2'), ('CA3', 'CA3'), ('CA4', 'CA4'), ('OBJECTIVE', 'Exam Objective'), ('THEORY', 'Exam Theory')], default='OBJECTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='examblueprint',
            name='theory_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examblueprint',
            name='theory_writeback_target',
            field=models.CharField(choices=[('NONE', 'No Writeback'), ('CA1', 'CA1'), ('CA2', 'CA2'), ('CA3', 'CA3'), ('CA4', 'CA4'), ('OBJECTIVE', 'Exam Objective'), ('THEORY', 'Exam Theory')], default='THEORY', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('OBJECTIVE', 'Objective'), ('MULTI_SELECT', 'Multi Select'), ('SHORT_ANSWER', 'Short Answer'), ('LABELING', 'Diagram Labeling'), ('MATCHING', 'Matching'), ('ORDERING', 'Drag/Drop Ordering')], default='OBJECTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('FINALIZED', 'Finalized')], default='IN_PROGRESS', max_length=20)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('objective_raw_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('objective_max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('objective_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('theory_raw_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('theory_max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('theory_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('auto_marking_completed', models.BooleanField(default=False)),
                ('theory_marking_completed', models.BooleanField(default=False)),
                ('writeback_completed', models.BooleanField(default=False)),
                ('writeback_metadata', models.JSONField(blank=True, default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cbt.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_text', models.TextField(blank=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('auto_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('teacher_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('teacher_marked_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cbt.examattempt')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='cbt.examquestion')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='attempt_answers', to='cbt.option')),
                ('teacher_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_marked_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('exam_question__sort_order',),
            },
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'student'], name='cbt_examatt_exam_id_ce4486_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'updated_at'], name='cbt_examatt_status_6120eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'attempt_number'), name='unique_attempt_number_per_exam_student'),
        ),
        migrations.AddConstraint(
            model_name='examattemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'exam_question'), name='unique_answer_per_exam_question_per_attempt'),
        ),
    ]
