# Generated by Django 5.2.11 on 2026-03-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_examblueprint_allow_retake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='active_tab_token',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='allow_resume_by_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='extra_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='lock_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
