# Generated by Django 5.2.11 on 2026-03-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_examattempt_active_tab_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(max_length=180)),
                ('tool_type', models.CharField(blank=True, max_length=80)),
                ('tool_category', models.CharField(choices=[('SCIENCE', 'Science'), ('MATHEMATICS', 'Mathematics'), ('ARTS', 'Arts'), ('HUMANITIES', 'Humanities'), ('BUSINESS', 'Business'), ('COMPUTER_SCIENCE', 'Computer Science')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('online_url', models.URLField(blank=True)),
                ('offline_asset_path', models.CharField(blank=True, max_length=255)),
                ('score_mode', models.CharField(choices=[('AUTO', 'Auto'), ('VERIFY', 'Verify'), ('RUBRIC', 'Rubric')], max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=7)),
                ('scoring_callback_type', models.CharField(default='POST_MESSAGE', max_length=64)),
                ('evidence_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_DEAN', 'Pending Dean'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('dean_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dean_review_comment', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_simulation_wrappers_created', to=settings.AUTH_USER_MODEL)),
                ('dean_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_simulation_wrappers_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('tool_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExamSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('writeback_target', models.CharField(choices=[('NONE', 'No Writeback'), ('CA1', 'CA1'), ('CA2', 'CA2'), ('CA3', 'CA3'), ('CA4', 'CA4'), ('OBJECTIVE', 'Exam Objective'), ('THEORY', 'Exam Theory')], default='CA3', max_length=20)),
                ('max_score_override', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_simulations', to='cbt.exam')),
                ('simulation_wrapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_links', to='cbt.simulationwrapper')),
            ],
            options={
                'ordering': ('exam_id', 'sort_order'),
            },
        ),
        migrations.CreateModel(
            name='SimulationAttemptRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('AUTO_CAPTURED', 'Auto Captured'), ('VERIFY_PENDING', 'Verify Pending'), ('VERIFIED', 'Verified'), ('RUBRIC_PENDING', 'Rubric Pending'), ('RUBRIC_SCORED', 'Rubric Scored'), ('IMPORTED', 'Imported')], default='NOT_STARTED', max_length=20)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='cbt/simulation_evidence/%Y/%m/')),
                ('evidence_note', models.TextField(blank=True)),
                ('verify_comment', models.TextField(blank=True)),
                ('rubric_breakdown', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('imported_target', models.CharField(choices=[('NONE', 'No Writeback'), ('CA1', 'CA1'), ('CA2', 'CA2'), ('CA3', 'CA3'), ('CA4', 'CA4'), ('OBJECTIVE', 'Exam Objective'), ('THEORY', 'Exam Theory')], default='NONE', max_length=20)),
                ('imported_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_attempts', to='cbt.examattempt')),
                ('exam_simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_records', to='cbt.examsimulation')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_imported_simulation_scores', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_verified_simulation_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('exam_simulation__sort_order',),
                'indexes': [models.Index(fields=['status', 'updated_at'], name='cbt_simulat_status_76c431_idx'), models.Index(fields=['attempt', 'status'], name='cbt_simulat_attempt_068c1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'exam_simulation'), name='unique_simulation_record_per_attempt')],
            },
        ),
        migrations.AddConstraint(
            model_name='simulationwrapper',
            constraint=models.UniqueConstraint(fields=('tool_name', 'tool_category'), name='unique_simulation_tool_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='examsimulation',
            constraint=models.UniqueConstraint(fields=('exam', 'simulation_wrapper'), name='unique_simulation_wrapper_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='examsimulation',
            constraint=models.UniqueConstraint(fields=('exam', 'sort_order'), name='unique_simulation_order_per_exam'),
        ),
    ]
