# Generated by Django 5.2.11 on 2026-03-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0004_simulationwrapper_examsimulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationwrapper',
            name='source_provider',
            field=models.CharField(choices=[('PHET', 'PhET'), ('H5P', 'H5P'), ('GEOGEBRA', 'GeoGebra'), ('DESMOS', 'Desmos'), ('LABXCHANGE', 'LabXchange'), ('PYODIDE', 'Pyodide/Skulpt'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
        migrations.AddField(
            model_name='simulationwrapper',
            name='source_reference_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulationwrapper',
            name='scoring_callback_type',
            field=models.CharField(choices=[('POST_MESSAGE', 'postMessage'), ('XAPI_STATEMENT', 'xAPI Statement'), ('H5P_XAPI', 'H5P xAPI'), ('PHET_WRAPPER', 'PhET Wrapper')], default='POST_MESSAGE', max_length=64),
        ),
    ]
