# Generated by Django 5.2.11 on 2026-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0005_simulationwrapper_source_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_free_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='rich_stem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='shared_stimulus_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='stimulus_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='stimulus_image',
            field=models.FileField(blank=True, null=True, upload_to='cbt/question_media/images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='question',
            name='stimulus_video',
            field=models.FileField(blank=True, null=True, upload_to='cbt/question_media/videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('CA', 'CA'), ('EXAM', 'Exam'), ('PRACTICAL', 'Practical'), ('SIM', 'Simulation'), ('FREE_TEST', 'Free Test')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_DEAN', 'Pending Dean'), ('PENDING_IT', 'Pending IT'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='examreviewaction',
            name='from_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_DEAN', 'Pending Dean'), ('PENDING_IT', 'Pending IT'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examreviewaction',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_DEAN', 'Pending Dean'), ('PENDING_IT', 'Pending IT'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], max_length=20),
        ),
    ]
