# Generated by Django 5.2.11 on 2026-03-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0006_exam_is_free_test_question_rich_stem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="activation_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="exam",
            name="activation_snapshot_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="integrity_bundle",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
