# Generated by Django 5.2.11 on 2026-03-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _disable_finalize_on_logout(apps, schema_editor):
    ExamBlueprint = apps.get_model("cbt", "ExamBlueprint")
    ExamBlueprint.objects.update(finalize_on_logout=False)



class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0007_exam_activation_snapshot_and_attempt_integrity_bundle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='timer_is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='timer_pause_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='timer_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='timer_paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_exam_timer_pauses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='timer_pause_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examblueprint',
            name='finalize_on_logout',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_disable_finalize_on_logout, migrations.RunPython.noop),
    ]
