# Generated by Django 5.2.11 on 2026-04-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0008_exam_timer_is_paused_exam_timer_pause_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='label',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
    ]
