# Generated by Django 5.2.11 on 2026-03-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='allow_staff_admin_voting',
            field=models.BooleanField(default=True),
        ),
    ]
