from __future__ import annotations

from apps.cbt.models import (
    CBTSimulationCallbackType,
    CBTSimulationScoreMode,
    CBTSimulationSourceProvider,
    CBTSimulationToolCategory,
)


CURATED_SIMULATION_CATALOG = [
    {
        "tool_name": "PhET Circuit Construction Kit",
        "tool_type": "HTML5 Simulation",
        "source_provider": CBTSimulationSourceProvider.PHET,
        "source_reference_url": "https://phet.colorado.edu/",
        "tool_category": CBTSimulationToolCategory.SCIENCE,
        "description": "Physics practical for building and testing DC circuits.",
        "online_url": "https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.AUTO,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.PHET_WRAPPER,
        "evidence_required": False,
    },
    {
        "tool_name": "PhET Projectile Motion Lab",
        "tool_type": "HTML5 Simulation",
        "source_provider": CBTSimulationSourceProvider.PHET,
        "source_reference_url": "https://phet.colorado.edu/",
        "tool_category": CBTSimulationToolCategory.SCIENCE,
        "description": "Physics practical for velocity, launch angle, and trajectory analysis.",
        "online_url": "https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_en.html",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.AUTO,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.PHET_WRAPPER,
        "evidence_required": False,
    },
    {
        "tool_name": "PhET Balancing Chemical Equations",
        "tool_type": "HTML5 Simulation",
        "source_provider": CBTSimulationSourceProvider.PHET,
        "source_reference_url": "https://phet.colorado.edu/",
        "tool_category": CBTSimulationToolCategory.SCIENCE,
        "description": "Chemistry practical for balancing and validating equations.",
        "online_url": "https://phet.colorado.edu/sims/html/balancing-chemical-equations/latest/balancing-chemical-equations_en.html",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.AUTO,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.PHET_WRAPPER,
        "evidence_required": False,
    },
    {
        "tool_name": "GeoGebra Geometry Construction",
        "tool_type": "Interactive Geometry",
        "source_provider": CBTSimulationSourceProvider.GEOGEBRA,
        "source_reference_url": "https://www.geogebra.org/",
        "tool_category": CBTSimulationToolCategory.MATHEMATICS,
        "description": "Geometry practical for construction, transformations, and locus tasks.",
        "online_url": "https://www.geogebra.org/classic",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.AUTO,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": False,
    },
    {
        "tool_name": "Desmos Graphing Practical",
        "tool_type": "Interactive Graphing",
        "source_provider": CBTSimulationSourceProvider.DESMOS,
        "source_reference_url": "https://www.desmos.com/",
        "tool_category": CBTSimulationToolCategory.MATHEMATICS,
        "description": "Graphing and function analysis practical.",
        "online_url": "https://www.desmos.com/calculator",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.AUTO,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": False,
    },
    {
        "tool_name": "H5P Interactive Timeline",
        "tool_type": "H5P Content",
        "source_provider": CBTSimulationSourceProvider.H5P,
        "source_reference_url": "https://h5p.org/content-types-and-applications",
        "tool_category": CBTSimulationToolCategory.HUMANITIES,
        "description": "History and civic timeline practical with graded interactions.",
        "online_url": "https://h5p.org/",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.AUTO,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
        "evidence_required": False,
    },
    {
        "tool_name": "H5P Grammar Spot-Check",
        "tool_type": "H5P Content",
        "source_provider": CBTSimulationSourceProvider.H5P,
        "source_reference_url": "https://h5p.org/content-types-and-applications",
        "tool_category": CBTSimulationToolCategory.HUMANITIES,
        "description": "English language practical using grammar and sentence correction tasks.",
        "online_url": "https://h5p.org/",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.AUTO,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
        "evidence_required": False,
    },
    {
        "tool_name": "H5P Home Economics Kitchen Safety",
        "tool_type": "H5P Content",
        "source_provider": CBTSimulationSourceProvider.H5P,
        "source_reference_url": "https://h5p.org/content-types-and-applications",
        "tool_category": CBTSimulationToolCategory.ARTS,
        "description": "Home economics practical for kitchen hygiene and safety workflows.",
        "online_url": "https://h5p.org/",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.VERIFY,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
        "evidence_required": True,
    },
    {
        "tool_name": "H5P Accounting Ledger Lab",
        "tool_type": "H5P Content",
        "source_provider": CBTSimulationSourceProvider.H5P,
        "source_reference_url": "https://h5p.org/content-types-and-applications",
        "tool_category": CBTSimulationToolCategory.BUSINESS,
        "description": "Commercial subject practical for journal/ledger entries and balancing.",
        "online_url": "https://h5p.org/",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.AUTO,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
        "evidence_required": False,
    },
    {
        "tool_name": "Pyodide Browser Coding Sandbox",
        "tool_type": "Browser Coding Runtime",
        "source_provider": CBTSimulationSourceProvider.PYODIDE,
        "source_reference_url": "https://pyodide.org/",
        "tool_category": CBTSimulationToolCategory.COMPUTER_SCIENCE,
        "description": "Computer science practical with browser-based Python execution.",
        "online_url": "https://pyodide.org/en/stable/console.html",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.RUBRIC,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": True,
    },
    {
        "tool_name": "LabXchange Biology Practical",
        "tool_type": "Virtual Lab",
        "source_provider": CBTSimulationSourceProvider.LABXCHANGE,
        "source_reference_url": "https://www.labxchange.org/",
        "tool_category": CBTSimulationToolCategory.SCIENCE,
        "description": "Biology practical for virtual microscopy and investigative tasks.",
        "online_url": "https://www.labxchange.org/",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.VERIFY,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": True,
    },
    {
        "tool_name": "PhET Acid-Base Solutions",
        "tool_type": "HTML5 Simulation",
        "source_provider": CBTSimulationSourceProvider.PHET,
        "source_reference_url": "https://phet.colorado.edu/",
        "tool_category": CBTSimulationToolCategory.SCIENCE,
        "description": "Chemistry practical focused on acids, bases, and pH behavior (HTML5/offline-capable).",
        "online_url": "https://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_en.html",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.VERIFY,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": True,
    },
    {
        "tool_name": "PhET Graphing Lines",
        "tool_type": "HTML5 Simulation",
        "source_provider": CBTSimulationSourceProvider.PHET,
        "source_reference_url": "https://phet.colorado.edu/",
        "tool_category": CBTSimulationToolCategory.MATHEMATICS,
        "description": "Mathematics practical for gradients, intercepts, and line transformations.",
        "online_url": "https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_en.html",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.VERIFY,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": True,
    },
    {
        "tool_name": "OpenStax Simulation Directory",
        "tool_type": "Simulation Catalog",
        "source_provider": CBTSimulationSourceProvider.OTHER,
        "source_reference_url": "https://openstax.org/",
        "tool_category": CBTSimulationToolCategory.SCIENCE,
        "description": "OpenStax collection entry point for physics/chemistry simulation activities.",
        "online_url": "https://openstax.org/subjects/science",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.VERIFY,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": True,
    },
    {
        "tool_name": "ChemCollective Virtual Lab",
        "tool_type": "Virtual Lab",
        "source_provider": CBTSimulationSourceProvider.OTHER,
        "source_reference_url": "https://chemcollective.org/",
        "tool_category": CBTSimulationToolCategory.SCIENCE,
        "description": "Chemistry virtual lab practical with worksheet-style tasks and offline options.",
        "online_url": "https://chemcollective.org/vlabs",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.VERIFY,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": True,
    },
    {
        "tool_name": "Virtual Labs (NMEICT)",
        "tool_type": "Virtual Lab Library",
        "source_provider": CBTSimulationSourceProvider.OTHER,
        "source_reference_url": "https://www.vlab.co.in/",
        "tool_category": CBTSimulationToolCategory.SCIENCE,
        "description": "Large virtual lab collection (validate per-topic fit/licensing before school rollout).",
        "online_url": "https://www.vlab.co.in/",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.VERIFY,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": True,
    },
    {
        "tool_name": "OLabs Practical Library",
        "tool_type": "Offline Practical Suite",
        "source_provider": CBTSimulationSourceProvider.OTHER,
        "source_reference_url": "https://www.olabs.edu.in/",
        "tool_category": CBTSimulationToolCategory.SCIENCE,
        "description": "Offline-capable practical simulation library (topic match to NDGA curriculum required).",
        "online_url": "https://www.olabs.edu.in/",
        "offline_asset_path": "",
        "score_mode": CBTSimulationScoreMode.VERIFY,
        "max_score": "10.00",
        "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
        "evidence_required": True,
    },
]

CURATED_SIMULATION_CATALOG.extend(
    [
        {
            "tool_name": "PhET Ohm's Law Practical",
            "tool_type": "HTML5 Simulation",
            "source_provider": CBTSimulationSourceProvider.PHET,
            "source_reference_url": "https://phet.colorado.edu/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Physics practical for Ohm's law, current-voltage relation, and resistor behavior.",
            "online_url": "https://phet.colorado.edu/sims/html/ohms-law/latest/ohms-law_en.html",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "PhET Pendulum Lab",
            "tool_type": "HTML5 Simulation",
            "source_provider": CBTSimulationSourceProvider.PHET,
            "source_reference_url": "https://phet.colorado.edu/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Physics practical for SHM period measurement, amplitude effects, and gravity effects.",
            "online_url": "https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_en.html",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "PhET Wave On A String",
            "tool_type": "HTML5 Simulation",
            "source_provider": CBTSimulationSourceProvider.PHET,
            "source_reference_url": "https://phet.colorado.edu/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Physics practical for wave speed, amplitude, frequency, and damping behavior.",
            "online_url": "https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_en.html",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "PhET Concentration Lab",
            "tool_type": "HTML5 Simulation",
            "source_provider": CBTSimulationSourceProvider.PHET,
            "source_reference_url": "https://phet.colorado.edu/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Chemistry practical for concentration, dilution, and molarity interpretation.",
            "online_url": "https://phet.colorado.edu/sims/html/concentration/latest/concentration_en.html",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "PhET pH Scale Basics",
            "tool_type": "HTML5 Simulation",
            "source_provider": CBTSimulationSourceProvider.PHET,
            "source_reference_url": "https://phet.colorado.edu/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Chemistry practical for acid/base strength and pH interpretation tasks.",
            "online_url": "https://phet.colorado.edu/sims/html/ph-scale-basics/latest/ph-scale-basics_en.html",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "PhET Natural Selection",
            "tool_type": "HTML5 Simulation",
            "source_provider": CBTSimulationSourceProvider.PHET,
            "source_reference_url": "https://phet.colorado.edu/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Biology practical for adaptation, selection pressure, and population outcomes.",
            "online_url": "https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_en.html",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "GeoGebra 3D Grapher",
            "tool_type": "3D Graphing",
            "source_provider": CBTSimulationSourceProvider.GEOGEBRA,
            "source_reference_url": "https://www.geogebra.org/",
            "tool_category": CBTSimulationToolCategory.MATHEMATICS,
            "description": "Mathematics practical for coordinate geometry and 3D graph exploration.",
            "online_url": "https://www.geogebra.org/3d",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.AUTO,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": False,
        },
        {
            "tool_name": "Desmos Scientific Graphing",
            "tool_type": "Graphing Calculator",
            "source_provider": CBTSimulationSourceProvider.DESMOS,
            "source_reference_url": "https://www.desmos.com/",
            "tool_category": CBTSimulationToolCategory.MATHEMATICS,
            "description": "Graphing practical for slope, intercept, transformation, and function interpretation.",
            "online_url": "https://www.desmos.com/calculator",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "ChemCollective Titration Virtual Lab",
            "tool_type": "Virtual Lab",
            "source_provider": CBTSimulationSourceProvider.OTHER,
            "source_reference_url": "https://chemcollective.org/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Chemistry practical for titration setup, endpoint interpretation, and calculation.",
            "online_url": "https://chemcollective.org/vlabs",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "Virtual Labs Electrical Measurements",
            "tool_type": "Virtual Lab",
            "source_provider": CBTSimulationSourceProvider.OTHER,
            "source_reference_url": "https://www.vlab.co.in/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Physics/electronics practical for meter reading, circuit assembly, and instrument use.",
            "online_url": "https://www.vlab.co.in/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "Virtual Labs Microscopy Practical",
            "tool_type": "Virtual Lab",
            "source_provider": CBTSimulationSourceProvider.OTHER,
            "source_reference_url": "https://www.vlab.co.in/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Biology practical for microscope handling and specimen observation workflow.",
            "online_url": "https://www.vlab.co.in/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "OLabs Physics Practical Set",
            "tool_type": "Offline Practical Suite",
            "source_provider": CBTSimulationSourceProvider.OTHER,
            "source_reference_url": "https://www.olabs.edu.in/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Physics practical suite for school-lab style experiments in offline mode.",
            "online_url": "https://www.olabs.edu.in/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "OLabs Chemistry Practical Set",
            "tool_type": "Offline Practical Suite",
            "source_provider": CBTSimulationSourceProvider.OTHER,
            "source_reference_url": "https://www.olabs.edu.in/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Chemistry practical suite for school-lab style experiments in offline mode.",
            "online_url": "https://www.olabs.edu.in/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "H5P Geography Map Practical",
            "tool_type": "Interactive Map",
            "source_provider": CBTSimulationSourceProvider.H5P,
            "source_reference_url": "https://h5p.org/",
            "tool_category": CBTSimulationToolCategory.HUMANITIES,
            "description": "Geography practical for map layers, coordinates, and regional identification.",
            "online_url": "https://h5p.org/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.RUBRIC,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
            "evidence_required": True,
        },
        {
            "tool_name": "H5P Agricultural Planning Lab",
            "tool_type": "Scenario Simulation",
            "source_provider": CBTSimulationSourceProvider.H5P,
            "source_reference_url": "https://h5p.org/",
            "tool_category": CBTSimulationToolCategory.ARTS,
            "description": "Agricultural science practical for crop planning and farm-process sequencing.",
            "online_url": "https://h5p.org/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.RUBRIC,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
            "evidence_required": True,
        },
        {
            "tool_name": "H5P Technical Drawing Practice",
            "tool_type": "Interactive Practical",
            "source_provider": CBTSimulationSourceProvider.H5P,
            "source_reference_url": "https://h5p.org/",
            "tool_category": CBTSimulationToolCategory.ARTS,
            "description": "Technical drawing practical with shape interpretation and projection tasks.",
            "online_url": "https://h5p.org/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.RUBRIC,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
            "evidence_required": True,
        },
        {
            "tool_name": "H5P Home Economics Practical",
            "tool_type": "Process Simulation",
            "source_provider": CBTSimulationSourceProvider.H5P,
            "source_reference_url": "https://h5p.org/",
            "tool_category": CBTSimulationToolCategory.ARTS,
            "description": "Home economics practical for kitchen workflow, hygiene, and nutrition tasks.",
            "online_url": "https://h5p.org/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.RUBRIC,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
            "evidence_required": True,
        },
        {
            "tool_name": "H5P Financial Accounting Trial Balance",
            "tool_type": "Interactive Ledger",
            "source_provider": CBTSimulationSourceProvider.H5P,
            "source_reference_url": "https://h5p.org/",
            "tool_category": CBTSimulationToolCategory.BUSINESS,
            "description": "Financial accounting practical for journals, ledgers, and trial balance tasks.",
            "online_url": "https://h5p.org/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.AUTO,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
            "evidence_required": False,
        },
        {
            "tool_name": "H5P Commerce Retail Scenario",
            "tool_type": "Scenario Simulation",
            "source_provider": CBTSimulationSourceProvider.H5P,
            "source_reference_url": "https://h5p.org/",
            "tool_category": CBTSimulationToolCategory.BUSINESS,
            "description": "Commerce practical for demand/supply and market scenario analysis.",
            "online_url": "https://h5p.org/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.RUBRIC,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.H5P_XAPI,
            "evidence_required": True,
        },
        {
            "tool_name": "Blockly Algorithm Practical",
            "tool_type": "Programming Sandbox",
            "source_provider": CBTSimulationSourceProvider.OTHER,
            "source_reference_url": "https://developers.google.com/blockly",
            "tool_category": CBTSimulationToolCategory.COMPUTER_SCIENCE,
            "description": "ICT practical for logic, flow, and algorithm block programming tasks.",
            "online_url": "https://developers.google.com/blockly",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.RUBRIC,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "Scratch Coding Studio",
            "tool_type": "Programming Sandbox",
            "source_provider": CBTSimulationSourceProvider.OTHER,
            "source_reference_url": "https://scratch.mit.edu/",
            "tool_category": CBTSimulationToolCategory.COMPUTER_SCIENCE,
            "description": "ICT practical for events, loops, and basic program design simulation tasks.",
            "online_url": "https://scratch.mit.edu/",
            "offline_asset_path": "",
            "score_mode": CBTSimulationScoreMode.RUBRIC,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "NDGA Graph Practical Board",
            "tool_type": "Interactive Graphing",
            "source_provider": CBTSimulationSourceProvider.OTHER,
            "source_reference_url": "https://ndgakuje.org/",
            "tool_category": CBTSimulationToolCategory.MATHEMATICS,
            "description": "Offline NDGA graph practical board for coordinate plotting, trend-line checks, and quick graph evidence.",
            "online_url": "",
            "offline_asset_path": "static/sims/ndga-graph-practical/index.html",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
        {
            "tool_name": "NDGA Virtual Microscope Lab",
            "tool_type": "Virtual Microscope",
            "source_provider": CBTSimulationSourceProvider.OTHER,
            "source_reference_url": "https://ndgakuje.org/",
            "tool_category": CBTSimulationToolCategory.SCIENCE,
            "description": "Offline NDGA microscope practical board for slide observation, magnification control, and specimen labeling evidence.",
            "online_url": "",
            "offline_asset_path": "static/sims/ndga-virtual-microscope/index.html",
            "score_mode": CBTSimulationScoreMode.VERIFY,
            "max_score": "10.00",
            "scoring_callback_type": CBTSimulationCallbackType.POST_MESSAGE,
            "evidence_required": True,
        },
    ]
)


def grouped_catalog_labels():
    display_map = dict(CBTSimulationToolCategory.choices)
    grouped = {}
    for item in CURATED_SIMULATION_CATALOG:
        category = display_map.get(item["tool_category"], item["tool_category"])
        grouped.setdefault(category, []).append(item["tool_name"])
    return grouped
