from django.urls import path

from apps.cbt.views import (
    CBTAIExamDraftView,
    CBTAuthoringHomeView,
    CBTHomeRedirectView,
    CBTDeanReviewDetailView,
    CBTDeanReviewListView,
    CBTExamBuilderView,
    CBTExamCreateView,
    CBTExamDeleteView,
    CBTExamDetailView,
    CBTExamQuestionAttachView,
    CBTExamSimulationPickerView,
    CBTSimulationLaunchView,
    CBTSimulationLibraryAPIView,
    CBTExamSimulationToolCreateView,
    CBTExamSimulationAttachView,
    CBTExamSubmitToDeanView,
    CBTDeanSimulationReviewDetailView,
    CBTDeanSimulationReviewListView,
    CBTITActivationDetailView,
    CBTITActivationListView,
    CBTITSimulationRegistryView,
    CBTQuestionBankCreateView,
    CBTQuestionCreateView,
    CBTQuestionEditView,
    CBTAttemptSimulationAutoScoreView,
    CBTAttemptHeartbeatView,
    CBTAttemptWarningView,
    CBTAttemptViolationView,
    CBTSimulationMarkingDetailView,
    CBTSimulationMarkingListView,
    CBTStudentSimulationSessionView,
    CBTStudentAttemptResultView,
    CBTStudentAttemptLockedView,
    CBTStudentAttemptRunView,
    CBTStudentExamListView,
    CBTStudentExamStartView,
    CBTITLockdownActionView,
    CBTITLockdownDashboardView,
    CBTTheoryMarkingDetailView,
    CBTTheoryMarkingListView,
    CBTUploadImportView,
)

app_name = "cbt"

urlpatterns = [
    path("", CBTHomeRedirectView.as_view(), name="home"),
    path("api/simulations/", CBTSimulationLibraryAPIView.as_view(), name="simulation-library-api"),
    path("simulator/launch/<int:wrapper_id>/", CBTSimulationLaunchView.as_view(), name="simulation-launch"),
    path("authoring/", CBTAuthoringHomeView.as_view(), name="authoring-home"),
    path("authoring/banks/new/", CBTQuestionBankCreateView.as_view(), name="bank-create"),
    path("authoring/questions/new/", CBTQuestionCreateView.as_view(), name="question-create"),
    path("authoring/questions/<int:question_id>/edit/", CBTQuestionEditView.as_view(), name="question-edit"),
    path("authoring/exams/new/", CBTExamCreateView.as_view(), name="exam-create"),
    path("authoring/exams/<int:exam_id>/delete/", CBTExamDeleteView.as_view(), name="exam-delete"),
    path("authoring/ai-draft/", CBTAIExamDraftView.as_view(), name="ai-draft"),
    path("authoring/exams/<int:exam_id>/builder/", CBTExamBuilderView.as_view(), name="exam-builder"),
    path(
        "authoring/exams/<int:exam_id>/simulations/",
        CBTExamSimulationPickerView.as_view(),
        name="exam-simulation-picker",
    ),
    path("authoring/exams/<int:exam_id>/", CBTExamDetailView.as_view(), name="exam-detail"),
    path(
        "authoring/exams/<int:exam_id>/attach-questions/",
        CBTExamQuestionAttachView.as_view(),
        name="exam-attach-questions",
    ),
    path(
        "authoring/exams/<int:exam_id>/attach-simulations/",
        CBTExamSimulationAttachView.as_view(),
        name="exam-attach-simulations",
    ),
    path(
        "authoring/exams/<int:exam_id>/simulation-tools/new/",
        CBTExamSimulationToolCreateView.as_view(),
        name="exam-simulation-tool-create",
    ),
    path(
        "authoring/exams/<int:exam_id>/submit-to-dean/",
        CBTExamSubmitToDeanView.as_view(),
        name="exam-submit-to-dean",
    ),
    path("authoring/upload/", CBTUploadImportView.as_view(), name="upload-import"),
    path("dean/review/", CBTDeanReviewListView.as_view(), name="dean-review-list"),
    path("dean/review/<int:exam_id>/", CBTDeanReviewDetailView.as_view(), name="dean-review-detail"),
    path("dean/simulations/", CBTDeanSimulationReviewListView.as_view(), name="dean-simulation-review-list"),
    path(
        "dean/simulations/<int:wrapper_id>/",
        CBTDeanSimulationReviewDetailView.as_view(),
        name="dean-simulation-review-detail",
    ),
    path("it/activation/", CBTITActivationListView.as_view(), name="it-activation-list"),
    path("it/activation/<int:exam_id>/", CBTITActivationDetailView.as_view(), name="it-activation-detail"),
    path("it/simulations/", CBTITSimulationRegistryView.as_view(), name="it-simulation-registry"),
    path("exams/available/", CBTStudentExamListView.as_view(), name="student-exam-list"),
    path("exams/<int:exam_id>/start/", CBTStudentExamStartView.as_view(), name="student-exam-start"),
    path("attempts/<int:attempt_id>/run/", CBTStudentAttemptRunView.as_view(), name="student-attempt-run"),
    path("attempts/<int:attempt_id>/result/", CBTStudentAttemptResultView.as_view(), name="student-attempt-result"),
    path(
        "attempts/<int:attempt_id>/simulations/<int:exam_simulation_id>/",
        CBTStudentSimulationSessionView.as_view(),
        name="student-simulation-session",
    ),
    path(
        "attempts/<int:attempt_id>/simulations/<int:exam_simulation_id>/auto-score/",
        CBTAttemptSimulationAutoScoreView.as_view(),
        name="attempt-simulation-auto-score",
    ),
    path("attempts/<int:attempt_id>/locked/", CBTStudentAttemptLockedView.as_view(), name="student-attempt-locked"),
    path("attempts/<int:attempt_id>/heartbeat/", CBTAttemptHeartbeatView.as_view(), name="attempt-heartbeat"),
    path("attempts/<int:attempt_id>/warning/", CBTAttemptWarningView.as_view(), name="attempt-warning"),
    path("attempts/<int:attempt_id>/violation/", CBTAttemptViolationView.as_view(), name="attempt-violation"),
    path("marking/theory/", CBTTheoryMarkingListView.as_view(), name="theory-marking-list"),
    path("marking/theory/<int:attempt_id>/", CBTTheoryMarkingDetailView.as_view(), name="theory-marking-detail"),
    path("marking/simulations/", CBTSimulationMarkingListView.as_view(), name="simulation-marking-list"),
    path(
        "marking/simulations/<int:record_id>/",
        CBTSimulationMarkingDetailView.as_view(),
        name="simulation-marking-detail",
    ),
    path("it/lockdown/", CBTITLockdownDashboardView.as_view(), name="it-lockdown-dashboard"),
    path("it/lockdown/<int:attempt_id>/action/", CBTITLockdownActionView.as_view(), name="it-lockdown-action"),
]
