# Generated by Django 5.2.11 on 2026-03-01 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('state', models.CharField(choices=[('BOOT_EMPTY', 'Boot Empty'), ('SESSION_CREATED', 'Session Created'), ('TERM_CREATED', 'Term Created'), ('CALENDAR_CONFIGURED', 'Calendar Configured'), ('CLASSES_CREATED', 'Classes Created'), ('SUBJECTS_CREATED', 'Subjects Created'), ('IT_READY', 'IT Ready')], default='BOOT_EMPTY', max_length=32)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.academicsession')),
                ('current_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.term')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_finalizations', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setup State',
                'verbose_name_plural': 'System Setup State',
            },
        ),
    ]
