# Generated by Django 5.2.11 on 2026-03-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_wizard', '0002_seed_setup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetupstate',
            name='state',
            field=models.CharField(choices=[('BOOT_EMPTY', 'Boot Empty'), ('SESSION_CREATED', 'Session Created'), ('TERM_CREATED', 'Term Created'), ('CALENDAR_CONFIGURED', 'Calendar Configured'), ('CLASSES_CREATED', 'Classes Created'), ('SUBJECTS_CREATED', 'Subjects Created'), ('CLASS_SUBJECTS_MAPPED', 'Class Subjects Mapped'), ('GRADE_SCALE_CONFIGURED', 'Grade Scale Configured'), ('IT_READY', 'IT Ready')], default='BOOT_EMPTY', max_length=32),
        ),
    ]
