# Generated by Django 5.2.11 on 2026-03-02 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('CBT_EXAM_ATTEMPT', 'CBT Exam Attempt'), ('CBT_SIMULATION_ATTEMPT', 'CBT Simulation Attempt'), ('ELECTION_VOTE_SUBMISSION', 'Election Vote Submission')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RETRY', 'Retry Scheduled'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('CONFLICT', 'Conflict')], default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('conflict_rule', models.CharField(choices=[('APPEND_ONLY', 'Append Only'), ('LAST_WRITE_WINS', 'Last Write Wins'), ('STRICT_UNIQUE', 'Strict Unique')], default='APPEND_ONLY', max_length=20)),
                ('conflict_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('object_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source_portal', models.CharField(blank=True, max_length=32)),
                ('local_node_id', models.CharField(blank=True, max_length=80)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=8)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('remote_reference', models.CharField(blank=True, max_length=150)),
                ('last_error', models.TextField(blank=True)),
                ('is_manual_import', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='sync_syncqu_status_76dcd5_idx'), models.Index(fields=['operation_type', 'status'], name='sync_syncqu_operati_fd3862_idx'), models.Index(fields=['created_at'], name='sync_syncqu_created_27aa50_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncTransferBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=12)),
                ('file_name', models.CharField(max_length=255)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_transfer_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['direction', 'created_at'], name='sync_synctr_directi_523f96_idx')],
            },
        ),
    ]
