# Generated by Django 5.2.11 on 2026-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncContentChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stream",
                    models.CharField(
                        choices=[("CBT_CONTENT", "CBT Content")],
                        default="CBT_CONTENT",
                        max_length=32,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("QUESTION_BANK", "Question Bank"),
                            ("QUESTION", "Question"),
                            ("OPTION", "Option"),
                            ("CORRECT_ANSWER", "Correct Answer"),
                            ("EXAM", "Exam"),
                            ("EXAM_BLUEPRINT", "Exam Blueprint"),
                            ("EXAM_QUESTION", "Exam Question"),
                            ("SIMULATION_WRAPPER", "Simulation Wrapper"),
                            ("EXAM_SIMULATION", "Exam Simulation"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("UPSERT", "Upsert"), ("DELETE", "Delete")],
                        default="UPSERT",
                        max_length=16,
                    ),
                ),
                ("object_pk", models.CharField(db_index=True, max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("source_node_id", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ("id",),
                "indexes": [
                    models.Index(fields=["stream", "id"], name="sync_syncco_stream_06f2ee_idx"),
                    models.Index(fields=["object_type", "object_pk"], name="sync_syncco_object__e58a9a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncPullCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stream", models.CharField(choices=[("CBT_CONTENT", "CBT Content")], max_length=32, unique=True)),
                ("last_remote_id", models.BigIntegerField(default=0)),
                ("last_pull_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ("stream",)},
        ),
    ]
