# Generated by Django 5.2.11 on 2026-03-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_synccontentchange_syncpullcursor"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="synccontentchange",
            old_name="sync_syncco_stream_06f2ee_idx",
            new_name="sync_syncco_stream_122f10_idx",
        ),
        migrations.RenameIndex(
            model_name="synccontentchange",
            old_name="sync_syncco_object__e58a9a_idx",
            new_name="sync_syncco_object__b54830_idx",
        ),
    ]
