# Generated by Django 5.2.11 on 2026-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_rename_sync_syncco_stream_06f2ee_idx_sync_syncco_stream_122f10_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncqueue",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("CBT_EXAM_ATTEMPT", "CBT Exam Attempt"),
                    ("CBT_SIMULATION_ATTEMPT", "CBT Simulation Attempt"),
                    ("CBT_CONTENT_CHANGE", "CBT Content Change"),
                    ("STUDENT_REGISTRATION_UPSERT", "Student Registration Upsert"),
                    ("ELECTION_VOTE_SUBMISSION", "Election Vote Submission"),
                    ("MODEL_RECORD_UPSERT", "Model Record Upsert"),
                    ("MODEL_RECORD_DELETE", "Model Record Delete"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="synccontentchange",
            name="stream",
            field=models.CharField(
                choices=[
                    ("CBT_CONTENT", "CBT Content"),
                    ("OUTBOX_EVENTS", "Outbox Events"),
                ],
                default="CBT_CONTENT",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="syncpullcursor",
            name="stream",
            field=models.CharField(
                choices=[
                    ("CBT_CONTENT", "CBT Content"),
                    ("OUTBOX_EVENTS", "Outbox Events"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="SyncModelBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_node_id", models.CharField(max_length=80)),
                ("model_label", models.CharField(max_length=120)),
                ("source_pk", models.CharField(max_length=120)),
                ("local_pk", models.CharField(db_index=True, max_length=120)),
            ],
            options={
                "ordering": ("model_label", "source_node_id", "source_pk"),
                "indexes": [models.Index(fields=["model_label", "local_pk"], name="sync_syncmo_model_l_caa0fd_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_node_id", "model_label", "source_pk"),
                        name="unique_sync_model_binding_source_ref",
                    )
                ],
            },
        ),
    ]
