# Generated by Django 5.2.11 on 2026-03-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_syncmodelbinding_generic_operations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='syncmodelbinding',
            new_name='sync_syncmo_model_l_450ff9_idx',
            old_name='sync_syncmo_model_l_caa0fd_idx',
        ),
    ]
