# Generated by Django 5.2.11 on 2026-03-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_rename_sync_syncmo_model_l_caa0fd_idx_sync_syncmo_model_l_450ff9_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('queue_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='sync.syncqueue')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['queue_row', 'created_at'], name='sync_syncqu_queue_r_b0d834_idx'), models.Index(fields=['event_type'], name='sync_syncqu_event_t_bc033e_idx')],
            },
        ),
    ]
