# Generated by Django 5.2.11 on 2026-04-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcalendar',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
