# Generated by Django 5.2.11 on 2026-03-01 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_identifier', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('PERMISSION', 'Permission'), ('RESULTS', 'Results'), ('CBT', 'CBT'), ('ELECTION', 'Election'), ('FINANCE', 'Finance'), ('LOCKDOWN', 'Lockdown'), ('SYSTEM', 'System')], max_length=24)),
                ('event_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DENIED', 'Denied')], max_length=24)),
                ('message', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['category', 'event_type'], name='audit_audit_categor_7f8259_idx'), models.Index(fields=['created_at'], name='audit_audit_created_7710b7_idx')],
            },
        ),
    ]
