# Generated by Django 5.2.11 on 2026-03-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='previous_event_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
