from django.urls import path

from apps.dashboard.feature_views import (
    ClubManagementView,
    DocumentVaultManagementView,
    StudentDigitalIDView,
    StudentDocumentVaultView,
    StudentIDVerificationView,
    StudentLearningHubView,
    StudentWeeklyChallengeView,
    TeacherLessonPlannerView,
    WeeklyChallengeManagementView,
)
from apps.dashboard.views import (
    BursarPortalView,
    CBTPortalView,
    ElectionPortalView,
    ITFeatureToggleView,
    ITPortalView,
    PortalSummaryFragmentView,
    PortalRootView,
    PrincipalPortalView,
    PrincipalElectionLiveView,
    PrincipalSettingsView,
    PrincipalStaffBiodataView,
    PrincipalStudentsBiodataView,
    StaffProfileView,
    StaffSettingsView,
    StaffPortalView,
    StudentAttendanceView,
    StudentPortalView,
    StudentProfileView,
    StudentSettingsView,
    StudentSubjectsView,
    StudentTranscriptView,
    VPPortalView,
    VPElectionLiveView,
    VPStaffBiodataView,
    VPStudentsBiodataView,
    health_check,
)

app_name = "dashboard"

urlpatterns = [
    path("", PortalRootView.as_view(), name="landing"),
    path("health/", health_check, name="health-check"),
    path("portal/summary-fragment/", PortalSummaryFragmentView.as_view(), name="portal-summary-fragment"),
    path("portal/student/", StudentPortalView.as_view(), name="student-portal"),
    path("portal/student/profile/", StudentProfileView.as_view(), name="student-profile"),
    path("portal/student/attendance/", StudentAttendanceView.as_view(), name="student-attendance"),
    path("portal/student/subjects/", StudentSubjectsView.as_view(), name="student-subjects"),
    path("portal/student/transcript/", StudentTranscriptView.as_view(), name="student-transcript"),
    path("portal/student/learning-hub/", StudentLearningHubView.as_view(), name="student-learning-hub"),
    path("portal/student/weekly-challenge/", StudentWeeklyChallengeView.as_view(), name="student-weekly-challenge"),
    path("portal/student/id-card/", StudentDigitalIDView.as_view(), name="student-id-card"),
    path("portal/student/documents/", StudentDocumentVaultView.as_view(), name="student-document-vault"),
    path("portal/student/settings/", StudentSettingsView.as_view(), name="student-settings"),
    path("portal/staff/", StaffPortalView.as_view(), name="staff-portal"),
    path("portal/staff/profile/", StaffProfileView.as_view(), name="staff-profile"),
    path("portal/staff/lesson-planner/", TeacherLessonPlannerView.as_view(), name="teacher-lesson-planner"),
    path("portal/staff/settings/", StaffSettingsView.as_view(), name="staff-settings"),
    path("portal/it/", ITPortalView.as_view(), name="it-portal"),
    path("portal/it/feature-toggle/", ITFeatureToggleView.as_view(), name="it-feature-toggle"),
    path("portal/it/documents/", DocumentVaultManagementView.as_view(), name="it-document-vault"),
    path("portal/it/weekly-challenge/", WeeklyChallengeManagementView.as_view(), name="weekly-challenge-manage"),
    path("portal/clubs/", ClubManagementView.as_view(), name="club-management"),
    path("portal/bursar/", BursarPortalView.as_view(), name="bursar-portal"),
    path("portal/vp/", VPPortalView.as_view(), name="vp-portal"),
    path("portal/vp/students/", VPStudentsBiodataView.as_view(), name="vp-students-biodata"),
    path("portal/vp/staff/", VPStaffBiodataView.as_view(), name="vp-staff-biodata"),
    path("portal/vp/election-live/", VPElectionLiveView.as_view(), name="vp-election-live"),
    path("portal/vp/documents/", DocumentVaultManagementView.as_view(), name="vp-document-vault"),
    path("portal/principal/", PrincipalPortalView.as_view(), name="principal-portal"),
    path("portal/principal/settings/", PrincipalSettingsView.as_view(), name="principal-settings"),
    path("portal/principal/students/", PrincipalStudentsBiodataView.as_view(), name="principal-students-biodata"),
    path("portal/principal/staff/", PrincipalStaffBiodataView.as_view(), name="principal-staff-biodata"),
    path("portal/principal/election-live/", PrincipalElectionLiveView.as_view(), name="principal-election-live"),
    path("portal/principal/documents/", DocumentVaultManagementView.as_view(), name="principal-document-vault"),
    path("portal/cbt/", CBTPortalView.as_view(), name="cbt-portal"),
    path("portal/election/", ElectionPortalView.as_view(), name="election-portal"),
    path("id/verify/<path:student_number>/", StudentIDVerificationView.as_view(), name="student-id-verify"),
]
