from django.urls import path

from apps.dashboard.feature_views import (
    ClubManagementView,
    DocumentVaultManagementView,
    StudentDigitalIDView,
    StudentDocumentVaultView,
    StudentIDVerificationView,
    StudentLearningHubView,
    StudentLMSView,
    StudentWeeklyChallengeView,
    TeacherLessonPlannerView,
    TeacherLMSView,
    WeeklyChallengeManagementView,
)
from apps.dashboard.admissions_views import (
    AdmissionsWorkflowBursarView,
    ITAdmissionsWorkflowView,
    PrincipalAdmissionsWorkflowView,
    VPAdmissionsWorkflowView,
)
from apps.dashboard.public_views import (
    PublicContactView,
    PublicContentPageView,
    PublicGalleryCategoryView,
    PublicLiveChatCreateView,
    PublicNewsDetailView,
    PublicRegistrationView,
)
from apps.dashboard.views import (
    AccountSecuritySettingsView,
    BursarPortalView,
    CBTPortalView,
    ElectionPortalView,
    ITFeatureToggleView,
    ITPortalView,
    LegacyCalendarRedirectView,
    LegacyNoticeRedirectView,
    PortalSummaryFragmentView,
    PortalRootView,
    PrincipalPortalView,
    PrincipalElectionLiveView,
    PrincipalSettingsView,
    PrincipalStaffBiodataView,
    PrincipalStudentsBiodataView,
    StaffProfileView,
    StaffAttendanceOverviewView,
    StaffSettingsView,
    StaffPortalView,
    StaffResultsOverviewView,
    StudentAttendanceView,
    StudentPortalView,
    StudentProfileView,
    StudentSettingsView,
    StudentSubjectsView,
    StudentTranscriptView,
    VPPortalView,
    VPElectionLiveView,
    VPStaffBiodataView,
    VPStudentsBiodataView,
    health_check,
)

app_name = "dashboard"

urlpatterns = [
    path("", PortalRootView.as_view(), name="landing"),
    path("about/", PublicContentPageView.as_view(page_slug="about"), name="public-about"),
    path("principal/", PublicContentPageView.as_view(page_slug="principal"), name="public-principal"),
    path(
        "about/mission-vision-values/",
        PublicContentPageView.as_view(page_slug="mission-vision-values"),
        name="public-mission-vision-values",
    ),
    path("about/leadership/", PublicContentPageView.as_view(page_slug="leadership"), name="public-leadership"),
    path("about/school-life/", PublicContentPageView.as_view(page_slug="school-life"), name="public-school-life"),
    path("academics/", PublicContentPageView.as_view(page_slug="academics"), name="public-academics"),
    path(
        "academics/junior-secondary/",
        PublicContentPageView.as_view(page_slug="junior-secondary"),
        name="public-junior-secondary",
    ),
    path(
        "academics/senior-secondary/",
        PublicContentPageView.as_view(page_slug="senior-secondary"),
        name="public-senior-secondary",
    ),
    path("academics/curriculum/", PublicContentPageView.as_view(page_slug="curriculum"), name="public-curriculum"),
    path(
        "academics/subjects-departments/",
        PublicContentPageView.as_view(page_slug="subjects-departments"),
        name="public-subjects-departments",
    ),
    path(
        "academics/ict-digital-learning/",
        PublicContentPageView.as_view(page_slug="ict-digital-learning"),
        name="public-ict-digital-learning",
    ),
    path(
        "academics/co-curricular-activities/",
        PublicContentPageView.as_view(page_slug="co-curricular-activities"),
        name="public-co-curricular-activities",
    ),
    path(
        "academics/learning-support/",
        PublicContentPageView.as_view(page_slug="learning-support"),
        name="public-learning-support",
    ),
    path(
        "academics/examinations-assessment/",
        PublicContentPageView.as_view(page_slug="examinations-assessment"),
        name="public-examinations-assessment",
    ),
    path("admissions/", PublicContentPageView.as_view(page_slug="admissions"), name="public-admissions"),
    path(
        "admissions/how-to-apply/",
        PublicContentPageView.as_view(page_slug="how-to-apply"),
        name="public-how-to-apply",
    ),
    path("admissions/registration/", PublicRegistrationView.as_view(), name="public-registration"),
    path("fees/", PublicContentPageView.as_view(page_slug="fees"), name="public-fees"),
    path(
        "hostel-boarding/",
        PublicContentPageView.as_view(page_slug="hostel-boarding"),
        name="public-hostel-boarding",
    ),
    path(
        "admissions/payment-information/",
        PublicContentPageView.as_view(page_slug="payment-information"),
        name="public-payment-information",
    ),
    path(
        "admissions/admission-faqs/",
        PublicContentPageView.as_view(page_slug="admission-faqs"),
        name="public-admission-faqs",
    ),
    path("life-at-ndga/", PublicContentPageView.as_view(page_slug="life-at-ndga"), name="public-life"),
    path("facilities/", PublicContentPageView.as_view(page_slug="facilities"), name="public-facilities"),
    path("gallery/", PublicContentPageView.as_view(page_slug="gallery"), name="public-gallery"),
    path("gallery/<slug:slug>/", PublicGalleryCategoryView.as_view(), name="public-gallery-category"),
    path("news/", PublicContentPageView.as_view(page_slug="news"), name="public-news"),
    path("news/<slug:slug>/", PublicNewsDetailView.as_view(), name="public-news-detail"),
    path("events/", PublicContentPageView.as_view(page_slug="events"), name="public-events"),
    path("contact/", PublicContactView.as_view(), name="public-contact"),
    path("live-chat/", PublicLiveChatCreateView.as_view(), name="public-live-chat"),
    path("calendar/", LegacyCalendarRedirectView.as_view(), name="legacy-calendar"),
    path("notice/", LegacyNoticeRedirectView.as_view(), name="legacy-notice"),
    path("health/", health_check, name="health-check"),
    path("portal/summary-fragment/", PortalSummaryFragmentView.as_view(), name="portal-summary-fragment"),
    path("portal/student/", StudentPortalView.as_view(), name="student-portal"),
    path("portal/student/profile/", StudentProfileView.as_view(), name="student-profile"),
    path("portal/student/attendance/", StudentAttendanceView.as_view(), name="student-attendance"),
    path("portal/student/subjects/", StudentSubjectsView.as_view(), name="student-subjects"),
    path("portal/student/transcript/", StudentTranscriptView.as_view(), name="student-transcript"),
    path("portal/student/learning-hub/", StudentLearningHubView.as_view(), name="student-learning-hub"),
    path("portal/student/lms/", StudentLMSView.as_view(), name="student-lms"),
    path("portal/student/weekly-challenge/", StudentWeeklyChallengeView.as_view(), name="student-weekly-challenge"),
    path("portal/student/id-card/", StudentDigitalIDView.as_view(), name="student-id-card"),
    path("portal/student/documents/", StudentDocumentVaultView.as_view(), name="student-document-vault"),
    path("portal/student/settings/", StudentSettingsView.as_view(), name="student-settings"),
    path("portal/staff/", StaffPortalView.as_view(), name="staff-portal"),
    path("portal/staff/profile/", StaffProfileView.as_view(), name="staff-profile"),
    path("portal/staff/results-overview/", StaffResultsOverviewView.as_view(), name="staff-results-overview"),
    path("portal/staff/attendance-overview/", StaffAttendanceOverviewView.as_view(), name="staff-attendance-overview"),
    path("portal/staff/lesson-planner/", TeacherLessonPlannerView.as_view(), name="teacher-lesson-planner"),
    path("portal/staff/lms/", TeacherLMSView.as_view(), name="teacher-lms"),
    path("portal/staff/settings/", StaffSettingsView.as_view(), name="staff-settings"),
    path("portal/it/", ITPortalView.as_view(), name="it-portal"),
    path("portal/it/admissions/", ITAdmissionsWorkflowView.as_view(), name="it-admissions-workflow"),
    path("portal/it/feature-toggle/", ITFeatureToggleView.as_view(), name="it-feature-toggle"),
    path("portal/it/documents/", DocumentVaultManagementView.as_view(), name="it-document-vault"),
    path("portal/it/weekly-challenge/", WeeklyChallengeManagementView.as_view(), name="weekly-challenge-manage"),
    path("portal/account/security/", AccountSecuritySettingsView.as_view(), name="account-security-settings"),
    path("portal/clubs/", ClubManagementView.as_view(), name="club-management"),
    path("portal/bursar/", BursarPortalView.as_view(), name="bursar-portal"),
    path("portal/bursar/admissions/", AdmissionsWorkflowBursarView.as_view(), name="bursar-admissions-workflow"),
    path("portal/vp/", VPPortalView.as_view(), name="vp-portal"),
    path("portal/vp/admissions/", VPAdmissionsWorkflowView.as_view(), name="vp-admissions-workflow"),
    path("portal/vp/students/", VPStudentsBiodataView.as_view(), name="vp-students-biodata"),
    path("portal/vp/staff/", VPStaffBiodataView.as_view(), name="vp-staff-biodata"),
    path("portal/vp/election-live/", VPElectionLiveView.as_view(), name="vp-election-live"),
    path("portal/vp/documents/", DocumentVaultManagementView.as_view(), name="vp-document-vault"),
    path("portal/principal/", PrincipalPortalView.as_view(), name="principal-portal"),
    path("portal/principal/admissions/", PrincipalAdmissionsWorkflowView.as_view(), name="principal-admissions-workflow"),
    path("portal/principal/settings/", PrincipalSettingsView.as_view(), name="principal-settings"),
    path("portal/principal/students/", PrincipalStudentsBiodataView.as_view(), name="principal-students-biodata"),
    path("portal/principal/staff/", PrincipalStaffBiodataView.as_view(), name="principal-staff-biodata"),
    path("portal/principal/election-live/", PrincipalElectionLiveView.as_view(), name="principal-election-live"),
    path("portal/principal/documents/", DocumentVaultManagementView.as_view(), name="principal-document-vault"),
    path("portal/cbt/", CBTPortalView.as_view(), name="cbt-portal"),
    path("portal/election/", ElectionPortalView.as_view(), name="election-portal"),
    path("id/verify/<path:student_number>/", StudentIDVerificationView.as_view(), name="student-id-verify"),
]
