ROLE_IT_MANAGER = "IT_MANAGER"
ROLE_DEAN = "DEAN"
ROLE_FORM_TEACHER = "FORM_TEACHER"
ROLE_SUBJECT_TEACHER = "SUBJECT_TEACHER"
ROLE_BURSAR = "BURSAR"
ROLE_VP = "VP"
ROLE_PRINCIPAL = "PRINCIPAL"
ROLE_STUDENT = "STUDENT"

ROLE_CHOICES = (
    (ROLE_IT_MANAGER, "IT Manager"),
    (ROLE_DEAN, "Dean"),
    (ROLE_FORM_TEACHER, "Form Teacher"),
    (ROLE_SUBJECT_TEACHER, "Subject Teacher"),
    (ROLE_BURSAR, "Bursar"),
    (ROLE_VP, "Vice Principal"),
    (ROLE_PRINCIPAL, "Principal"),
    (ROLE_STUDENT, "Student"),
)

HIGH_TRUST_PASSWORD_ROLES = {ROLE_PRINCIPAL, ROLE_VP, ROLE_BURSAR}
ROLE_GROUP_STAFF = "STAFF"
ROLE_GROUP_ADMIN = "ADMIN"
ROLE_GROUP_STAFF_CODES = {
    ROLE_SUBJECT_TEACHER,
    ROLE_FORM_TEACHER,
    ROLE_DEAN,
}
ROLE_GROUP_ADMIN_CODES = {
    ROLE_BURSAR,
    ROLE_VP,
    ROLE_PRINCIPAL,
}
STAFF_REGISTRATION_ROLE_CODES = tuple(
    sorted(ROLE_GROUP_STAFF_CODES | ROLE_GROUP_ADMIN_CODES)
)
STAFF_ROLE_CODES = {
    ROLE_IT_MANAGER,
    ROLE_DEAN,
    ROLE_FORM_TEACHER,
    ROLE_SUBJECT_TEACHER,
    ROLE_BURSAR,
    ROLE_VP,
    ROLE_PRINCIPAL,
}

STAFF_ROLE_ID_PREFIX = {
    ROLE_DEAN: "DAN",
    ROLE_FORM_TEACHER: "FNB",
    ROLE_SUBJECT_TEACHER: "SNB",
    ROLE_BURSAR: "BUR",
    ROLE_VP: "VPP",
    ROLE_PRINCIPAL: "PRN",
}

PORTAL_ROLE_ACCESS = {
    "student": {ROLE_STUDENT},
    "staff": {ROLE_SUBJECT_TEACHER},
    "dean": {ROLE_DEAN},
    "form": {ROLE_FORM_TEACHER},
    "it": {ROLE_IT_MANAGER},
    "bursar": {ROLE_BURSAR},
    "vp": {ROLE_VP},
    "principal": {ROLE_PRINCIPAL},
    "cbt": STAFF_ROLE_CODES | {ROLE_STUDENT},
    "election": STAFF_ROLE_CODES | {ROLE_STUDENT},
    "audit": {ROLE_IT_MANAGER, ROLE_PRINCIPAL},
}

ROLE_HOME_PORTAL = {
    ROLE_STUDENT: "student",
    ROLE_IT_MANAGER: "it",
    ROLE_BURSAR: "bursar",
    ROLE_VP: "vp",
    ROLE_PRINCIPAL: "principal",
    ROLE_DEAN: "dean",
    ROLE_FORM_TEACHER: "form",
    ROLE_SUBJECT_TEACHER: "staff",
}
