# Generated by Django 5.2.11 on 2026-03-02 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_studentclassenrollment'),
        ('results', '0002_classresultcompilation_classresultstudentrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('TERM_REPORT', 'Term Report'), ('TRANSCRIPT', 'Transcript')], max_length=24)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('source_label', models.CharField(blank=True, max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('compilation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_artifacts', to='results.classresultcompilation')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdf_artifacts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_artifacts', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_artifacts', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_artifacts', to='academics.term')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['document_type', 'student', 'created_at'], name='pdfs_pdfart_documen_f37343_idx'), models.Index(fields=['payload_hash'], name='pdfs_pdfart_payload_ca7c73_idx')],
            },
        ),
    ]
