# Generated by Django 5.2.11 on 2026-03-03 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_academicsession_closed_at_academicsession_closed_by_and_more'),
        ('pdfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_compilation_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transcript_session_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_records', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_session_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('session__name', 'student__username'),
                'indexes': [models.Index(fields=['student', 'session'], name='pdfs_transc_student_cf5494_idx'), models.Index(fields=['payload_hash'], name='pdfs_transc_payload_bc01b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'session'), name='unique_transcript_session_record_per_student_session')],
            },
        ),
    ]
