# Generated by Django 5.2.11 on 2026-03-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0002_transcriptsessionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfartifact',
            name='document_type',
            field=models.CharField(choices=[('TERM_REPORT', 'Term Report'), ('TRANSCRIPT', 'Transcript'), ('PERFORMANCE_ANALYSIS', 'Performance Analysis')], max_length=24),
        ),
    ]
