# Generated by Codex on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0003_alter_pdfartifact_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfartifact",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("TERM_REPORT", "Term Report"),
                    ("CUMULATIVE_REPORT", "Cumulative Promotion Report"),
                    ("TRANSCRIPT", "Transcript"),
                    ("PERFORMANCE_ANALYSIS", "Performance Analysis"),
                ],
                max_length=24,
            ),
        ),
    ]
