# Generated by Django 5.2.11 on 2026-04-16 23:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReplyThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread_key', models.CharField(max_length=32, unique=True)),
                ('scope', models.CharField(choices=[('GENERAL', 'General'), ('FINANCE', 'Finance')], default='GENERAL', max_length=16)),
                ('subject', models.CharField(max_length=180)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_label', models.CharField(blank=True, max_length=180)),
                ('reply_to_email', models.EmailField(max_length=254, unique=True)),
                ('source_event', models.CharField(blank=True, max_length=64)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_reply_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_message_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EmailReplyMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], max_length=16)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('in_reply_to_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=180)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_signature', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_reply_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.emailreplythread')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='emailreplythread',
            index=models.Index(fields=['scope', 'last_message_at'], name='notificatio_scope_20896f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailreplythread',
            index=models.Index(fields=['recipient_email', 'last_message_at'], name='notificatio_recipie_bbbb68_idx'),
        ),
        migrations.AddIndex(
            model_name='emailreplythread',
            index=models.Index(fields=['source_event', 'last_message_at'], name='notificatio_source__18c5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailreplymessage',
            index=models.Index(fields=['thread', 'created_at'], name='notificatio_thread__88c38b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailreplymessage',
            index=models.Index(fields=['direction', 'created_at'], name='notificatio_directi_2d7530_idx'),
        ),
        migrations.AddIndex(
            model_name='emailreplymessage',
            index=models.Index(fields=['received_at'], name='notificatio_receive_1f0f01_idx'),
        ),
    ]
