# Generated by Django 5.2.11 on 2026-06-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_birthdaycontact_birthdaydispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaycontact',
            name='student_admission_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='birthdaycontact',
            name='student_name',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
